sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2 
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/ebooklib.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git

- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt
- asciidoctor -a toc,idprefix=xx_,version=$VERSION -b xhtml5 -T ./asciidoctor-htmlbook/htmlbook-autogen/
  -d book book.asciidoc -o book.html
- git clone https://github.com/gitenberg-dev/HTMLBook

# make book.html available to jinja2 environment by putting it into templates
- cp book.html asciidoctor-htmlbook/gitberg-machine/templates/

- /usr/bin/python asciidoctor-htmlbook/gitberg-machine/machine.py -o . -m metadata.yaml book.html
- xsltproc -stringparam external.assets.list " " ./HTMLBook/htmlbook-xsl/epub.xsl book.html
- cp ./HTMLBook/stylesheets/epub/epub.css OEBPS
- if [ -e cover.jpg ]; then cp cover.jpg OEBPS/cover.jpg; fi
# look for first images directory and one found, copy over to ./OEBPS
- find . -name images -type d | head -n 1 | xargs -I {} mv {} ./OEBPS/
- zip -rX book.epub mimetype
- zip -rX book.epub OEBPS/ META-INF/
- if test -d "OEBPS/images/"; then zip -rX book.epub OEBPS/images/ ;fi
- mv book.epub The-Communist-Manifesto.epub
- ebook-convert The-Communist-Manifesto.epub The-Communist-Manifesto.mobi
- xvfb-run ebook-convert The-Communist-Manifesto.epub The-Communist-Manifesto.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jvh45STD465ZYEF4KcaoZPkfNtWcCK75yNbtzwN6sPb3dP6MrAAoPpDMYxDSR8NYQAMDeTHgGMMcB3YakcxNzZr0E1koSgT3a1E2p63tl8Uy94vV3tqj6C6nZG0fSQdeflZ4sia6vTbVU0DbiJPIZGfAdC6/QfokX7yHMWWLK3a7bVFkbZt11I+8XLqmMgoei10M9sBhUHrssAY1NU8wgrMs2sAcVBX8q/OhjVlWwRLlbJxYmRxiioIL39vEYs6uo1F2NmjUGntJ4rJuGUDCZlMaVWKe8CL29xcyscHy0WovrLbkkVIX1KwyfcGqGOadBj3eljHk+lgwBnqCuiSaQZ1/j+RFuYkPgtrUW4z2diJioGfoikT6IMTARrIDJk6D2H05NAjxr4ze9n0OtguotC9DJMkDORM3ro09d98g1MWsup3AKWBXx0T3gkn/3K2SirAIiz+x0CgtHtA2P4lFMnxzjumlKLhOUKwwI+7QnQaGCenGEUhDOdyqn1J4lR+hBd13t0A+SlPoDpudKg96fLkCLrdvxiFUXw8SBRtMAFHOy08rji5FbM4l6RXnDYC6O0jXTSn0LHbvy6oFHajK9kpmKBZSKEVWDfJw5xXJgugaXjT/2Q/saWCM70QWcxV3tP1ekfskNKmUrd2IwO/RCQ6rQWDtC0w45ZZsOAIot/U=
  file:
    - The-Communist-Manifesto.epub
    - The-Communist-Manifesto.mobi
    - The-Communist-Manifesto.pdf
  "on":
    repo: GITenberg/The-Communist-Manifesto_61
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre